spring:
  datasource:
    url: jdbc:sqlserver://cgfinopsdbserver.database.windows.net:1433;database=EmployeeDB;user=finopsteamadmin@cgfinopsdbserver;password=Capgemini@20;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: finopsteamadmin
#    password: Capgemini@20

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect


server:
  port: 7070
  
test: hello world

